name: method-diff

on:
  push:
    paths:
      - 'Calculator.java'
  workflow_dispatch:

jobs:
  method-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code with History
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for full history and diffs

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Save previous and current versions of Calculator.java
        run: |
          git show HEAD~1:Calculator.java > Calculator_Old.java
          cp Calculator.java Calculator.java

      - name: Download GumTree CLI
        run: |
          wget https://github.com/GumTreeDiff/gumtree/releases/download/v2.1.1/gumtree-2.1.1.jar -O gumtree.jar

      - name: Run GumTree Diff
        run: |
          java -jar gumtree.jar textdiff Calculator_Old.java Calculator.java > gumtree-diff.txt
          cat gumtree-diff.txt

      - name: Simulate Test Based on GumTree Output
        run: |
          echo "Simulated test based on method changes detected by GumTree"
          # You can add test logic here later based on diff output
